memberaudit/urls.py
"""Define routes for Member Audit."""

from django.urls import path

from memberaudit.views import (
    admin,
    character_finder,
    character_viewer_1,
    character_viewer_2,
    data_export,
    launcher,
    reports,
)

app_name = "memberaudit"

urlpatterns = [
    # launcher
    path("", launcher.index, name="index"),
    path("launcher", launcher.launcher, name="launcher"),
    path("add_character", launcher.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        launcher.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        launcher.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        launcher.unshare_character,
        name="unshare_character",
    ),
    path("player_count_data", launcher.player_count_data, name="player_count_data"),
    # character viewer
    path(
        "character_viewer/<int:character_pk>/",
        character_viewer_1.character_viewer,
        name="character_viewer",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        character_viewer_1.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        character_viewer_1.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        character_viewer_1.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        character_viewer_1.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_fw_stats/<int:character_pk>/",
        character_viewer_1.character_fw_stats,
        name="character_fw_stats",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        character_viewer_1.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        character_viewer_1.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        character_viewer_2.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        character_viewer_2.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        character_viewer_2.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        character_viewer_2.character_mail,
        name="character_mail",
    ),
    path(
        "character_mining_ledger_data/<int:character_pk>/",
        character_viewer_2.character_mining_ledger_data,
        name="character_mining_ledger_data",
    ),
    path(
        "character_planets_data/<int:character_pk>/",
        character_viewer_2.character_planets_data,
        name="character_planets_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        character_viewer_2.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        character_viewer_2.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        character_viewer_2.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        character_viewer_2.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_standings_data/<int:character_pk>/",
        character_viewer_2.character_standings_data,
        name="character_standings_data",
    ),
    path(
        "character_titles_data/<int:character_pk>/",
        character_viewer_2.character_titles_data,
        name="character_titles_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        character_viewer_2.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        character_viewer_2.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        character_viewer_2.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        character_viewer_1.character_attribute_data,
        name="character_attribute_data",
    ),
    # character finder
    path(
        "character_finder", character_finder.character_finder, name="character_finder"
    ),
    path(
        "character_finder_data",
        character_finder.CharacterFinderListJson.as_view(),
        name="character_finder_data",
    ),
    path(
        "character_finder_list_fdd_data",
        character_finder.character_finder_list_fdd_data,
        name="character_finder_list_fdd_data",
    ),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "user_compliance_report_data",
        reports.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        reports.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        reports.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    # data export
    path("data-export/", data_export.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        data_export.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        data_export.download_export_file,
        name="download_export_file",
    ),
    # admin
    path(
        "admin/create-skillset-from-fitting",
        admin.admin_create_skillset_from_fitting,
        name="admin_create_skillset_from_fitting",
    ),
    path(
        "admin/create-skill-set-from-skill-plan",
        admin.admin_create_skillset_from_skill_plan,
        name="admin_create_skillset_from_skill_plan",
    ),
]

memberaudit/views/launcher.py
"""Launcher views."""

import datetime as dt

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission
from django.db import transaction
from django.db.models import Sum
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from esi.decorators import token_required

from allianceauth.eveonline.models import EveCharacter
from allianceauth.notifications import notify
from allianceauth.services.hooks import get_extension_logger
from app_utils.django import users_with_permission
from app_utils.logging import LoggerAddTag

from memberaudit import __title__, tasks
from memberaudit.app_settings import MEMBERAUDIT_TASKS_NORMAL_PRIORITY
from memberaudit.core import player_count
from memberaudit.models import (
    Character,
    CharacterMiningLedgerEntry,
    CharacterSkillpoints,
    CharacterWalletBalance,
    CharacterWalletJournalEntry,
    ComplianceGroupDesignation,
)

from ._common import add_common_context

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("memberaudit.basic_access")
def index(request):
    """Render index view."""
    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def launcher(request) -> HttpResponse:
    """Render launcher view."""
    context_1 = _dashboard_panel(request)
    context_2 = _characters_panel(request)
    context = add_common_context(request, {**context_1, **context_2})
    return render(request, "memberaudit/launcher.html", context)


def _dashboard_panel(request: HttpRequest) -> dict:
    """Render context for dashboard panel."""
    characters = list(Character.objects.owned_by_user(request.user))
    total_wallet_isk = CharacterWalletBalance.objects.filter(
        character__in=characters
    ).aggregate(Sum("total"))["total__sum"]

    mining_entries = CharacterMiningLedgerEntry.objects.filter(character__in=characters)
    today = dt.date.today()
    total_mined_isk = (
        mining_entries.filter(date__year=today.year, date__month=today.month)
        .annotate_pricing()
        .aggregate(Sum("total"))["total__sum"]
    ) or 0

    wallet_entries = CharacterWalletJournalEntry.objects.filter(
        character__in=characters
    )
    today = dt.date.today()
    total_ratted_isk = (
        wallet_entries.filter(
            ref_type="bounty_prizes",
            date__year=today.year,
            date__month=today.month,
        ).aggregate(Sum("amount"))["amount__sum"]
        or 0
    )

    total_character_skillpoints = CharacterSkillpoints.objects.filter(
        character__in=characters
    ).aggregate(Sum("total"))["total__sum"]

    known_characters_count = EveCharacter.objects.filter(
        character_ownership__user=request.user
    ).count()
    registered_count = len(characters)
    try:
        registered_percent = round(registered_count / known_characters_count * 100)
    except ZeroDivisionError:
        registered_percent = None

    context = {
        "registered_count": registered_count,
        "known_characters_count": known_characters_count,
        "registered_percent": registered_percent,
        "total_wallet_isk": total_wallet_isk,
        "total_mined_isk": total_mined_isk,
        "total_ratted_isk": total_ratted_isk,
        "total_character_skillpoints": total_character_skillpoints,
    }
    return context


def _characters_panel(request: HttpRequest) -> dict:
    """Render context for character panel."""
    owned_chars_query = (
        EveCharacter.objects.filter(character_ownership__user=request.user)
        .select_related(
            "memberaudit_character",
            "memberaudit_character__location",
            "memberaudit_character__location__eve_solar_system",
            "memberaudit_character__location__location__eve_solar_system",
            "memberaudit_character__location__location__eve_solar_system__eve_constellation__eve_region",
            "memberaudit_character__skillpoints",
            "memberaudit_character__unread_mail_count",
            "memberaudit_character__wallet_balance",
        )
        .order_by("character_name")
    )
    has_auth_characters = owned_chars_query.exists()
    auth_characters = []
    unregistered_chars = []
    for eve_character in owned_chars_query:
        try:
            character: Character = eve_character.memberaudit_character
        except AttributeError:
            unregistered_chars.append(eve_character.character_name)
        else:
            auth_characters.append(
                {
                    "character_id": eve_character.character_id,
                    "character_name": eve_character.character_name,
                    "character": character,
                    "total_update_status": character.calc_total_update_status(),
                    "needs_refresh": character.is_disabled
                    or character.has_token_issue(),
                    "alliance_id": eve_character.alliance_id,
                    "alliance_name": eve_character.alliance_name,
                    "corporation_id": eve_character.corporation_id,
                    "corporation_name": eve_character.corporation_name,
                }
            )

    unregistered_chars = sorted(unregistered_chars)
    characters_need_token_refresh = sorted(
        obj["character_name"] for obj in auth_characters if obj["needs_refresh"]
    )

    try:
        main_character_id = request.user.profile.main_character.character_id
    except AttributeError:
        main_character_id = None

    context = {
        "page_title": _("My Characters"),
        "auth_characters": auth_characters,
        "has_auth_characters": has_auth_characters,
        "unregistered_chars": unregistered_chars,
        "has_registered_characters": len(auth_characters) > 0,
        "main_character_id": main_character_id,
        "characters_need_token_refresh": characters_need_token_refresh,
    }

    return context


@login_required
@permission_required("memberaudit.basic_access")
@token_required(scopes=Character.get_esi_scopes())
def add_character(request, token) -> HttpResponse:
    """Render add character view."""
    eve_character = get_object_or_404(EveCharacter, character_id=token.character_id)
    with transaction.atomic():
        character = Character.objects.update_or_create(
            eve_character=eve_character, defaults={"is_disabled": False}
        )[0]
    tasks.update_character.apply_async(
        kwargs={
            "character_pk": character.pk,
            "force_update": True,
            "ignore_stale": True,
        },
        priority=MEMBERAUDIT_TASKS_NORMAL_PRIORITY,
    )
    messages.success(
        request,
        format_html(
            "<strong>{}</strong> {}",
            eve_character,
            _(
                "has been registered. "
                "Note that it can take a minute until all character data is visible."
            ),
        ),
    )
    if ComplianceGroupDesignation.objects.exists():
        tasks.update_compliance_groups_for_user.apply_async(
            args=[request.user.pk], priority=MEMBERAUDIT_TASKS_NORMAL_PRIORITY
        )
    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def remove_character(request, character_pk: int) -> HttpResponse:
    """Render remove character view."""
    try:
        character = Character.objects.select_related(
            "eve_character__character_ownership__user", "eve_character"
        ).get(pk=character_pk)
    except Character.DoesNotExist:
        return HttpResponseNotFound(f"Character with pk {character_pk} not found")
    if character.user and character.user == request.user:
        character_name = character.eve_character.character_name

        # Notify that character has been dropped
        permission_to_notify = Permission.objects.select_related("content_type").get(
            content_type__app_label=Character._meta.app_label,
            codename="notified_on_character_removal",
        )
        title = _("%s: Character has been removed!") % __title__
        message = _("%(user)s has removed character %(character)s") % {
            "user": request.user,
            "character": character_name,
        }
        for to_notify in users_with_permission(permission_to_notify):
            if character.user_has_scope(to_notify):
                notify(user=to_notify, title=title, message=message, level="INFO")

        character.delete()
        messages.success(
            request, _("Removed character %s as requested.") % character_name
        )
        if ComplianceGroupDesignation.objects.exists():
            tasks.update_compliance_groups_for_user.apply_async(
                args=[request.user.pk], priority=MEMBERAUDIT_TASKS_NORMAL_PRIORITY
            )
    else:
        return HttpResponseForbidden(
            f"No permission to remove Character with pk {character_pk}"
        )
    return redirect("memberaudit:launcher")


@login_required
@permission_required(["memberaudit.basic_access", "memberaudit.share_characters"])
def share_character(request, character_pk: int) -> HttpResponse:
    """Render share character view."""
    try:
        character = Character.objects.select_related(
            "eve_character__character_ownership__user", "eve_character"
        ).get(pk=character_pk)
    except Character.DoesNotExist:
        return HttpResponseNotFound(f"Character with pk {character_pk} not found")
    if character.user and character.user == request.user:
        character.is_shared = True
        character.save()
    else:
        return HttpResponseForbidden(

memberaudit/templates/memberaudit/partials/launcher/characters.html
{% load i18n %}
{% load evelinks %}
{% load memberaudit %}


<div class="panel panel-default">
    <div class="panel-heading" style="display:flex;">
        <h3 class="panel-title">{% translate 'Characters' %}</h3>
    </div>
    <div class="panel-body">
        <!-- Characters -->
        <div class="character-cards">
            <ul class="cards_container">
                <!-- Add New Character -->
                <li class="cards_item">
                    <div class="card">
                        <div class="card-header">{% translate 'Register Character' %}</div>

                        <div class="card-body card__content">
                            <a href="{% url 'memberaudit:add_character' %}">
                                <img src="{{ 1|character_portrait_url:256 }}" alt="Add character">
                            </a>
                        </div>

                        <div class="card-footer">
                            <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:add_character' %}">{% translate 'Register' %}</a>
                        </div>
                    </div>
                </li>

                {% if has_registered_characters %}
                    <!-- Registered Characters -->
                    {% for auth_character in auth_characters|dictsort:"character_name" %}
                        <li class="cards_item">
                            <div class="card">
                                <div class="card-header">
                                    {% include 'memberaudit/partials/character_name.html' with total_update_status=auth_character.total_update_status %}
                                </div>

                                <div class="card-body card__content">
                                    <p>
                                        <a href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}">
                                            <span class="aa-memberaudit-launcher-character-image">
                                                <img src="{{ auth_character.character_id|character_portrait_url:256 }}" alt="{{ auth_character.character_name }}">

                                                {% if auth_character.alliance_id %}
                                                    <span class="aa-memberaudit-alliance-logo">
                                                        <img class="" src="{{ auth_character.alliance_id|alliance_logo_url:64 }}" title="{{ auth_character.alliance_name }}">
                                                    </span>
                                                {% endif %}

                                                <span class="aa-memberaudit-corporation-logo">
                                                    <img class="" src="{{ auth_character.corporation_id|corporation_logo_url:64 }}" title="{{ auth_character.corporation_name }}">
                                                </span>
                                            </span>
                                        </a>
                                    </p>

                                    <div class="text-center">
                                        {% include 'memberaudit/partials/solar_system.html' with character=auth_character.character only %}<br>
                                        {% if auth_character.character.wallet_balance %}
                                            {% natural_number auth_character.character.wallet_balance.total %} ISK<br>
                                        {% else %}
                                            <span class="text-muted">{% translate "(no data yet)" %}</span>
                                        {% endif %}

                                    </div>
                                </div>

                                <div class="card-footer">
                                    <a class="btn btn-success btn-sm" href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}"
                                        role="button" title="{% translate 'View this character.' %}">
                                        <i class="fas fa-sign-in-alt"></i>
                                    </a>

                                    {% if perms.memberaudit.share_characters %}
                                        {% if auth_character.character.is_shared %}
                                            <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:unshare_character' auth_character.character.pk %}"
                                                role="button" title="{% translate 'Disable access to this character for recruiters.' %}">
                                                <i class="far fa-eye-slash"></i>
                                            </a>
                                        {% else %}
                                            {% blocktranslate asvar confirm_share_message %}Are you sure you want to allow others to see this character?{% endblocktranslate %}
                                            <a class="btn btn-warning btn-sm" href="{% url 'memberaudit:share_character' auth_character.character.pk %}"
                                                role="button"
                                                onclick="return confirm('{{ confirm_share_message }}')"
                                                title="{% translate 'Allow others to see this character.' %}">
                                                <i class="far fa-eye"></i>
                                            </a>
                                        {% endif %}
                                    {% endif %}

                                    {% blocktranslate asvar confirm_remove_message %}Are you sure you want to remove this character?{% endblocktranslate %}
                                    <a class="btn btn-danger btn-sm" href="{% url 'memberaudit:remove_character' auth_character.character.pk %}"
                                        role="button" title="{% translate 'Remove this character.' %}"
                                        onclick="return confirm('{{ confirm_remove_message }}')">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>

        {% if characters_need_token_refresh|length > 0 %}
            <p class="text-warning">
                <strong>
                <i class="fas fa-exclamation-triangle"></i>
                {% translate 'Please re-register characters with issues:' %}&nbsp;&nbsp;</strong>
                {{ characters_need_token_refresh|join:", " }}
            </p>
        {% endif %}

        {% if unregistered_chars|length > 0 %}
            <p class="text-warning">
                <strong>
                <i class="fas fa-exclamation-triangle"></i>
                {% translate 'Please register unregistered characters:' %}&nbsp;&nbsp;</strong>
                {{ unregistered_chars|join:", " }}
            </p>
        {% endif %}

        <p class="text-muted">
            <i class="fas fa-crown"></i> {% translate 'Main character' %}&nbsp;|&nbsp;
            <i class="far fa-eye"></i> {% translate 'Currently shared with others' %}&nbsp;|&nbsp;
            ⬤ {% translate 'Update status' %}
        </p>
    </div>
</div>

memberaudit/templates/memberaudit/partials/launcher/dashboard.html
{% load i18n %}
{% load memberaudit %}


<div id="memberaudit-dashboard">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">{% translate 'Dashboard' %}</div>
        </div>

        <div class="panel-body">
            <div class="memberaudit-dashboard-panels">
                <!-- Online Players -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="fas fa-server"></i>
                            {% comment %} <i class="fa-solid fa-server"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Online Players" %}
                            </span>

                            <span
                                class="memberaudit-dashboard-item-value"
                                id="dashboard-player-count"
                                data-url="{% url 'memberaudit:player_count_data' %}">
                                ?
                            </span>
                        </span>
                    </div>
                </div>

                <!-- Registered characters -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="fas fa-user-friends"></i>
                            {% comment %} <i class="fa-solid fa-user-group"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Registered Characters" %}
                            </span>

                            <span class="memberaudit-dashboard-item-value">
                                {{ registered_count }} ({{ registered_percent|default_if_none:"?" }}%)
                            </span>
                        </span>
                    </div>
                </div>

                <!-- Total character ISK -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="fas fa-wallet"></i>
                            {% comment %} <i class="fa-solid fa-wallet"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Total Wallet ISK" %}
                            </span>

                            <span class="memberaudit-dashboard-item-value">
                                {% natural_number total_wallet_isk %}
                            </span>
                        </span>
                    </div>
                </div>

                <!-- Total Mining ISK -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="far fa-gem"></i>
                            {% comment %} <i class="fa-regular fa-gem"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Total Mined ISK" %} <small>{% translate "(this month)" %}</small>
                            </span>

                            <span class="memberaudit-dashboard-item-value">
                                {% natural_number total_mined_isk %}
                            </span>
                        </span>
                    </div>
                </div>

                <!-- Total Ratted ISK -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="far fa-money-bill-alt"></i>
                            {% comment %} <i class="fa-regular fa-money-bill-1"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Total Ratted ISK" %} <small>{% translate "(this month)" %}</small>
                            </span>

                            <span class="memberaudit-dashboard-item-value">
                                {% natural_number total_ratted_isk %}
                            </span>
                        </span>
                    </div>
                </div>

                <!-- Total Character Skillpoints -->
                <div class="panel panel-default memberaudit-dashboard-item">
                    <div class="panel-body">
                        <span class="memberaudit-dashboard-item-icon">
                            <i class="fas fa-graduation-cap"></i>
                            {% comment %} <i class="fa-solid fa-graduation-cap"></i> {% endcomment %}
                        </span>

                        <span class="memberaudit-dashboard-item-wrapper">
                            <span class="memberaudit-dashboard-item-title">
                                {% translate "Total Character Skillpoints" %}
                            </span>

                            {% natural_number total_character_skillpoints %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>