memberaudit/urls.py
"""Define routes for Member Audit."""

from django.urls import path

from memberaudit.views import (
    admin,
    character_finder,
    character_viewer_1,
    character_viewer_2,
    data_export,
    launcher,
    reports,
)

app_name = "memberaudit"

urlpatterns = [
    # launcher
    path("", launcher.index, name="index"),
    path("launcher", launcher.launcher, name="launcher"),
    path("add_character", launcher.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        launcher.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        launcher.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        launcher.unshare_character,
        name="unshare_character",
    ),
    path("player_count_data", launcher.player_count_data, name="player_count_data"),
    # character viewer
    path(
        "character_viewer/<int:character_pk>/",
        character_viewer_1.character_viewer,
        name="character_viewer",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        character_viewer_1.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        character_viewer_1.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        character_viewer_1.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        character_viewer_1.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_fw_stats/<int:character_pk>/",
        character_viewer_1.character_fw_stats,
        name="character_fw_stats",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        character_viewer_1.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        character_viewer_1.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        character_viewer_2.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        character_viewer_2.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        character_viewer_2.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        character_viewer_2.character_mail,
        name="character_mail",
    ),
    path(
        "character_mining_ledger_data/<int:character_pk>/",
        character_viewer_2.character_mining_ledger_data,
        name="character_mining_ledger_data",
    ),
    path(
        "character_planets_data/<int:character_pk>/",
        character_viewer_2.character_planets_data,
        name="character_planets_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        character_viewer_2.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        character_viewer_2.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        character_viewer_2.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        character_viewer_2.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_standings_data/<int:character_pk>/",
        character_viewer_2.character_standings_data,
        name="character_standings_data",
    ),
    path(
        "character_titles_data/<int:character_pk>/",
        character_viewer_2.character_titles_data,
        name="character_titles_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        character_viewer_2.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        character_viewer_2.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        character_viewer_2.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        character_viewer_1.character_attribute_data,
        name="character_attribute_data",
    ),
    # character finder
    path(
        "character_finder", character_finder.character_finder, name="character_finder"
    ),
    path(
        "character_finder_data",
        character_finder.CharacterFinderListJson.as_view(),
        name="character_finder_data",
    ),
    path(
        "character_finder_list_fdd_data",
        character_finder.character_finder_list_fdd_data,
        name="character_finder_list_fdd_data",
    ),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "user_compliance_report_data",
        reports.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        reports.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        reports.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    # data export
    path("data-export/", data_export.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        data_export.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        data_export.download_export_file,
        name="download_export_file",
    ),
    # admin
    path(
        "admin/create-skillset-from-fitting",
        admin.admin_create_skillset_from_fitting,
        name="admin_create_skillset_from_fitting",
    ),
    path(
        "admin/create-skill-set-from-skill-plan",
        admin.admin_create_skillset_from_skill_plan,
        name="admin_create_skillset_from_skill_plan",
    ),
]

memberaudit/models/character_sections_1.py
"""
Character sections models
"""

from typing import Optional

from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from eveuniverse.models import EveEntity, EveType

from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from memberaudit import __title__
from memberaudit.helpers import EveEntityIdsMixin
from memberaudit.managers.character_sections_1 import (
    CharacterAssetManager,
    CharacterAttributesManager,
    CharacterContactLabelManager,
    CharacterContactManager,
    CharacterContractBidManager,
    CharacterContractItemManager,
    CharacterContractManager,
)

from ._helpers import AddGenericReprMixin
from .characters import Character
from .constants import CURRENCY_MAX_DECIMALS, CURRENCY_MAX_DIGITS, NAMES_MAX_LENGTH
from .general import Location

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


class CharacterAsset(AddGenericReprMixin, models.Model):
    """An Eve Online asset belonging to a character."""

    id = models.BigAutoField(primary_key=True)

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="assets"
    )
    item_id = models.PositiveBigIntegerField()

    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, default=None, null=True
    )
    parent = models.ForeignKey(
        "CharacterAsset",
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="children",
    )

    eve_type = models.ForeignKey(EveType, on_delete=models.CASCADE, related_name="+")
    is_blueprint_copy = models.BooleanField(default=None, null=True, db_index=True)
    is_singleton = models.BooleanField()
    location_flag = models.CharField(max_length=NAMES_MAX_LENGTH)
    name = models.CharField(max_length=NAMES_MAX_LENGTH, default="")
    quantity = models.PositiveIntegerField()

    objects = CharacterAssetManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "item_id"],
                name="functional_pk_characterasset",
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.item_id}-{self.name_display}"

    @property
    def name_display(self) -> str:
        """Return name of this asset to be displayed to user."""
        name = self.name if self.name else self.eve_type.name
        if self.is_blueprint_copy:
            name += " [BPC]"
        return name

    @property
    def icon_url(self) -> str:
        """Return URL for an icon."""
        variant = self.eve_type.IconVariant.BPC if self.is_blueprint_copy else None
        return self.eve_type.icon_url(variant=variant)

    @property
    def group_display(self) -> str:
        """Return group name of this asset to be displayed to user."""
        return self.eve_type.name if self.name else self.eve_type.eve_group.name


class CharacterAttributes(AddGenericReprMixin, models.Model):
    """The training attributes of a character."""

    character = models.OneToOneField(
        Character,
        primary_key=True,
        on_delete=models.CASCADE,
        related_name="attributes",
        help_text="character these attributes belongs to",
    )

    accrued_remap_cooldown_date = models.DateTimeField(default=None, null=True)
    last_remap_date = models.DateTimeField(default=None, null=True)
    bonus_remaps = models.PositiveIntegerField()
    charisma = models.PositiveIntegerField()
    intelligence = models.PositiveIntegerField()
    memory = models.PositiveIntegerField()
    perception = models.PositiveIntegerField()
    willpower = models.PositiveIntegerField()
    objects = CharacterAttributesManager()

    class Meta:
        default_permissions = ()

    def __str__(self) -> str:
        return str(self.character)


class CharacterCloneInfo(AddGenericReprMixin, models.Model):
    """General clone infos for this character."""

    character = models.OneToOneField(
        Character, on_delete=models.CASCADE, related_name="clone_info"
    )

    home_location = models.ForeignKey(
        Location, on_delete=models.CASCADE, null=True, default=None
    )
    last_clone_jump_date = models.DateTimeField(default=None, null=True)
    last_station_change_date = models.DateTimeField(default=None, null=True)

    class Meta:
        default_permissions = ()

    def __str__(self) -> str:
        return str(self.character)


class CharacterContactLabel(AddGenericReprMixin, models.Model):
    """An Eve Online contact label belonging to a Character."""

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="contact_labels"
    )
    label_id = models.PositiveBigIntegerField()
    name = models.CharField(max_length=NAMES_MAX_LENGTH)

    objects = CharacterContactLabelManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "label_id"], name="functional_pk_characterlabel"
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.name}"


class CharacterContact(AddGenericReprMixin, models.Model):
    """An Eve Online contact belonging to a Character."""

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="contacts"
    )
    eve_entity = models.ForeignKey(
        EveEntity, on_delete=models.CASCADE, related_name="+"
    )

    is_blocked = models.BooleanField(default=None, null=True)
    is_watched = models.BooleanField(default=None, null=True)
    standing = models.FloatField()
    labels = models.ManyToManyField(CharacterContactLabel, related_name="contacts")

    objects = CharacterContactManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "eve_entity"],
                name="functional_pk_charactercontact",
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.eve_entity.name}"


class CharacterContract(EveEntityIdsMixin, AddGenericReprMixin, models.Model):
    """An Eve Online contract belonging to a Character"""

    AVAILABILITY_ALLIANCE = "AL"
    AVAILABILITY_CORPORATION = "CO"
    AVAILABILITY_PERSONAL = "PR"
    AVAILABILITY_PUBLIC = "PU"
    AVAILABILITY_CHOICES = (
        (AVAILABILITY_ALLIANCE, _("alliance")),
        (AVAILABILITY_CORPORATION, _("corporation")),
        (AVAILABILITY_PERSONAL, _("private")),
        (AVAILABILITY_PUBLIC, _("public")),
    )
    ESI_AVAILABILITY_MAP = {
        "alliance": AVAILABILITY_ALLIANCE,
        "corporation": AVAILABILITY_CORPORATION,
        "personal": AVAILABILITY_PERSONAL,
        "public": AVAILABILITY_PUBLIC,
    }

    STATUS_OUTSTANDING = "OS"
    STATUS_IN_PROGRESS = "IP"
    STATUS_FINISHED_ISSUER = "FI"
    STATUS_FINISHED_CONTRACTOR = "FC"
    STATUS_FINISHED = "FS"
    STATUS_CANCELED = "CA"
    STATUS_REJECTED = "RJ"
    STATUS_FAILED = "FL"
    STATUS_DELETED = "DL"
    STATUS_REVERSED = "RV"
    STATUS_CHOICES = (
        (STATUS_CANCELED, _("canceled")),
        (STATUS_DELETED, _("deleted")),
        (STATUS_FAILED, _("failed")),
        (STATUS_FINISHED, _("finished")),
        (STATUS_FINISHED_CONTRACTOR, _("finished contractor")),
        (STATUS_FINISHED_ISSUER, _("finished issuer")),
        (STATUS_IN_PROGRESS, _("in progress")),
        (STATUS_OUTSTANDING, _("outstanding")),
        (STATUS_REJECTED, _("rejected")),
        (STATUS_REVERSED, _("reversed")),
    )
    ESI_STATUS_MAP = {
        "canceled": STATUS_CANCELED,
        "deleted": STATUS_DELETED,
        "failed": STATUS_FAILED,
        "finished": STATUS_FINISHED,
        "finished_contractor": STATUS_FINISHED_CONTRACTOR,
        "finished_issuer": STATUS_FINISHED_ISSUER,
        "in_progress": STATUS_IN_PROGRESS,
        "outstanding": STATUS_OUTSTANDING,
        "rejected": STATUS_REJECTED,
        "reversed": STATUS_REVERSED,
    }

    TYPE_AUCTION = "AT"
    TYPE_COURIER = "CR"
    TYPE_ITEM_EXCHANGE = "IE"
    TYPE_LOAN = "LN"
    TYPE_UNKNOWN = "UK"
    TYPE_CHOICES = (
        (TYPE_AUCTION, _("auction")),
        (TYPE_COURIER, _("courier")),
        (TYPE_ITEM_EXCHANGE, _("item exchange")),
        (TYPE_LOAN, _("loan")),
        (TYPE_UNKNOWN, _("unknown")),
    )
    ESI_TYPE_MAP = {
        "auction": TYPE_AUCTION,
        "courier": TYPE_COURIER,
        "item_exchange": TYPE_ITEM_EXCHANGE,
        "loan": TYPE_LOAN,
        "unknown": TYPE_UNKNOWN,
    }

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="contracts"
    )
    contract_id = models.IntegerField()

    acceptor = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="Who will accept the contract if character",
    )
    acceptor_corporation = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="corporation of acceptor",
    )  # TODO: This field is currently unused
    assignee = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="To whom the contract is assigned, can be a corporation or a character",
    )
    availability = models.CharField(
        max_length=2,
        choices=AVAILABILITY_CHOICES,
        help_text="To whom the contract is available",
    )
    buyout = models.DecimalField(
        max_digits=CURRENCY_MAX_DIGITS,
        decimal_places=CURRENCY_MAX_DECIMALS,
        default=None,
        null=True,
    )
    collateral = models.DecimalField(
        max_digits=CURRENCY_MAX_DIGITS,

memberaudit/templates/memberaudit/modals/character_viewer/asset_container.html
{% load i18n %}
{% load static %}
{% load humanize %}

<!-- Modal for Contracts -->
<div class="modal" id="modalCharacterAssetContainer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-xl" role="document" id="modalCharacterAssetContainerContent">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
                    &times;
                </span></button>
                <h4 class="modal-title" id="myModalLabel">{% translate 'Loading...' %}</h4>
            </div>

            <div class="modal-body">
                {% if NIGHT_MODE %}
                    <img src="{% static 'memberaudit/images/Spinner-1s-64px-dark.gif' %}"/>
                {% else %}
                    <img src="{% static 'memberaudit/images/Spinner-1s-64px-light.gif' %}"/>
                {% endif %}
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    {% translate 'Close' %}
                </button>
            </div>
        </div>
    </div>
</div>

memberaudit/templates/memberaudit/modals/character_viewer/asset_container_content.html
{% load humanize %}
{% load i18n %}
{% load memberaudit %}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
            &times;
        </span></button>
        <h4 class="modal-title" id="myModalLabel">{% translate 'Asset Container' %}</h4>
    </div>

    <div class="modal-body">
        {% if error %}
            <p class="text-danger">{{ error }}</p>
        {% else %}
            <ol class="breadcrumb">
                <li>{{ parent_asset.location.name }}</li>
                <li class="active"><img src="{{ parent_asset_icon_url }}"/>&nbsp;&nbsp;{{ parent_asset.name_display }} ({{ parent_asset.group_display }})</li>
            </ol>

            <div class="table-responsive">
                <table class="table table-striped table-width-fix" id="tab_asset_children">
                    <thead>
                        <tr>
                            <th>{% translate 'Name' %}</th>
                            <th>{% translate 'Qty' %}</th>
                            <th>{% translate 'Group' %}</th>
                            <th>{% translate 'Volume' %}</th>
                            <th>{% translate 'Price' %}</th>
                            <th>{% translate 'Total' %}</th>
                        </tr>
                    </thead>

                    <tbody> </tbody>

                    <tfoot>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>{% translate 'Grand Total:' %}</th>
                        <th></th>
                    </tfoot>
                </table>
            </div>
        {% endif %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            {% translate 'Close' %}
        </button>
    </div>
</div>

<script>
    {% if parent_asset %}
        $(document).ready(function () {
            $('#tab_asset_children').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_asset_container_data' character.pk parent_asset.pk %}",
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    { data: 'name',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    {
                        data: 'quantity',
                        render: $.fn.dataTable.render.number( ',', '.', 0 )
                    },
                    { data: 'group' },
                    {
                        data: 'volume',
                        render: $.fn.dataTable.render.number( ',', '.', 2 )
                    },
                    {
                        data: 'price',
                        render: $.fn.dataTable.render.number( ',', '.', 2 )
                    },
                    {
                        data: 'total',
                        render: $.fn.dataTable.render.number( ',', '.', 2 )
                    },
                ],
                order: [[0, "asc"], [1, "asc"]],
                footerCallback: function ( row, data, start, end, display ) {
                    var api = this.api(), data;

                    // Remove the formatting to get integer data for summation
                    var intVal = function ( i ) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '')*1 :
                            typeof i === 'number' ?
                                i : 0;
                    };

                    // Total over all pages
                    var total = api
                        .column( 5 )
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Update footer
                    $( api.column( 5 ).footer() ).html(
                        total.toLocaleString()
                    );
                }
            });
        });
    {% endif %}
</script>

memberaudit/templates/memberaudit/modals/character_viewer/contract_content.html
{% load humanize %}
{% load i18n %}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
            &times;
        </span></button>
        <h4 class="modal-title" id="myModalLabel">{{ contract_summary }}</h4>
    </div>
    <div class="modal-body">
        {% if error %}
            <p class="text-danger">{{ error }}</p>
        {% else %}
            <dl class="dl-horizontal">
                <dt>{% translate 'Info by Issuer:' %}</dt> <dd>{{ contract.title|default:"(None)" }}</dd>
                <dt>{% translate 'Type:' %}</dt> <dd>{{ contract.get_contract_type_display|title }}</dd>
                <dt>{% translate 'Issued By:' %}</dt> <dd>{{ contract.issuer.name }}</dd>
                <dt>{% translate 'Availability:' %}</dt>
                <dd>
                    {{ contract.get_availability_display|title }}
                    {% if contract.availability == contract.AVAILABILITY_PUBLIC  %}
                        - {% translate 'Region:' %} {{ contract.start_location.eve_solar_system.eve_constellation.eve_region }}
                    {% else %}
                        - {{ contract.assignee.name }}
                    {% endif %}
                </dd>
                <dt>{% translate 'Status:' %}</dt> <dd>{{ contract.get_status_display|title }}</dd>
                <dt>{% translate 'Location:' %}</dt>
                <dd>
                    <a href="{{ contract.start_location.solar_system_url }}" target="_blank">
                        {{ contract.start_location.name }}
                    </a>
                </dd>
                <dt>{% translate 'Date Issued:' %}</dt> <dd>{{ contract.date_issued|date:MY_DATETIME_FORMAT }}</dd>
                <dt>{% translate 'Expiration Date:' %}</dt> <dd>{{ contract.date_expired|date:MY_DATETIME_FORMAT }}</dd>
                <hr>
                {% if contract.contract_type == contract.TYPE_COURIER %}
                    <dt>{% translate 'Complete In:' %}</dt> <dd>{{ contract.days_to_complete }}</dd>
                    <dt>{% translate 'Volume:' %}</dt> <dd>{{ contract.volume|floatformat:2|intcomma }} {% translate 'm3' %}</dd>
                    <dt>{% translate 'Reward:' %}</dt> <dd>{{ contract.reward|floatformat:2|intcomma }} {% translate 'ISK' %}</dd>
                    <dt>{% translate 'Collateral:' %}</dt> <dd>{{ contract.collateral|floatformat:2|intcomma }}</dd>
                    <dt>{% translate 'Destination:' %}</dt>
                    <dd>
                        <a href="{{ contract.end_location.solar_system_url }}" target="_blank">
                            {{ contract.end_location.name }}
                        </a>
                    </dd>
                {% elif contract.contract_type == contract.TYPE_ITEM_EXCHANGE %}
                    {% if contract.price or has_items_requested %}
                        <h4 class="text-danger">{% translate 'Buyer will pay' %}</h4>
                        {% if contract.price %}
                            <p>{{ contract.price|floatformat:2|intcomma }} {% translate 'ISK' %}</p>
                        {% endif %}
                        {% if has_items_requested %}
                            {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_requested" %}
                        {% endif %}
                    {% endif %}

                    <hr>

                    {% if contract.reward or has_items_included %}
                        <h4 class="text-success">{% translate 'Buyer will get' %}</h4>
                        {% if contract.reward %}
                            <p>{{ contract.reward|floatformat:2|intcomma }} {% translate 'ISK' %}</p>
                        {% endif %}
                        {% if has_items_included %}
                            {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_included" %}
                        {% endif %}
                    {% endif %}
                {% elif contract.contract_type == contract.TYPE_AUCTION %}
                    <dt>{% translate 'Starting Bid:' %}</dt> <dd>{{ contract.price|floatformat:2|intcomma }}</dd>
                    <dt>{% translate 'Buyout Price:' %}</dt> <dd>{{ contract.buyout|floatformat:2|intcomma }}</dd>
                    <dt>{% translate 'Current Bid:' %}</dt> <dd>{{ current_bid|floatformat:2|intcomma }} ({{ bids_count }} {% translate 'so far' %})</dd>
                    <dt>{% translate 'Time Left:' %}</dt> <dd>{{ contract.date_expired|timeuntil }}</dd>

                    <hr>

                    <h4 class="text-success">{% translate 'Buyer will get' %}</h4>
                    {% if has_items_included %}
                        {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_included" %}
                    {% endif %}
                {% endif %}
            </dl>
        {% endif %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            {% translate 'Close' %}
        </button>
    </div>
</div>

<script>
    $(document).ready(function () {
        {% if has_items_requested or has_items_included %}
            var columns = [
                { data: 'name',
                    render: {
                        _: 'display',
                        sort: 'sort'
                    }
                },
                {
                    data: 'quantity',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                { data: 'group' },
                { data: 'category' },
                {
                    data: 'price',
                    render: $.fn.dataTable.render.number( ',', '.', 2 )
                },
                {
                    data: 'total',
                    render: $.fn.dataTable.render.number( ',', '.', 2 )
                }
            ]
            var order = [[0, "asc"]]
            var footerCallback = function ( row, data, start, end, display ) {
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var intVal = function ( i ) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '')*1 :
                        typeof i === 'number' ?
                            i : 0;
                };

                // Total over all pages
                var total = api
                    .column( 5 )
                    .data()
                    .reduce( function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0 );

                // Update footer
                $( api.column( 5 ).footer() ).html(
                    total.toLocaleString(
                        {minimumFractionDigits: 2, maximumFractionDigits: 2}
                    )
                );
            }
        {% endif %}
        {% if has_items_requested %}
            $('#tab_contract_items_requested').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_contract_items_requested_data' character.pk contract.pk %}",
                    dataSrc: 'data',
                    cache: false
                },
                columns: columns,
                order: order,
                footerCallback: footerCallback
            });
        {% endif %}

        {% if has_items_included %}
            $('#tab_contract_items_included').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_contract_items_included_data' character.pk contract.pk %}",
                    dataSrc: 'data',
                    cache: false
                },
                columns: columns,
                order: order,
                footerCallback: footerCallback
            });
        {% endif %}
    });
</script>