memberaudit/urls.py
"""Define routes for Member Audit."""

from django.urls import path

from memberaudit.views import (
    admin,
    character_finder,
    character_viewer_1,
    character_viewer_2,
    data_export,
    launcher,
    reports,
)

app_name = "memberaudit"

urlpatterns = [
    # launcher
    path("", launcher.index, name="index"),
    path("launcher", launcher.launcher, name="launcher"),
    path("add_character", launcher.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        launcher.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        launcher.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        launcher.unshare_character,
        name="unshare_character",
    ),
    path("player_count_data", launcher.player_count_data, name="player_count_data"),
    # character viewer
    path(
        "character_viewer/<int:character_pk>/",
        character_viewer_1.character_viewer,
        name="character_viewer",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        character_viewer_1.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        character_viewer_1.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        character_viewer_1.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        character_viewer_1.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_fw_stats/<int:character_pk>/",
        character_viewer_1.character_fw_stats,
        name="character_fw_stats",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        character_viewer_1.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        character_viewer_1.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        character_viewer_2.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        character_viewer_2.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        character_viewer_2.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        character_viewer_2.character_mail,
        name="character_mail",
    ),
    path(
        "character_mining_ledger_data/<int:character_pk>/",
        character_viewer_2.character_mining_ledger_data,
        name="character_mining_ledger_data",
    ),
    path(
        "character_planets_data/<int:character_pk>/",
        character_viewer_2.character_planets_data,
        name="character_planets_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        character_viewer_2.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        character_viewer_2.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        character_viewer_2.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        character_viewer_2.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_standings_data/<int:character_pk>/",
        character_viewer_2.character_standings_data,
        name="character_standings_data",
    ),
    path(
        "character_titles_data/<int:character_pk>/",
        character_viewer_2.character_titles_data,
        name="character_titles_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        character_viewer_2.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        character_viewer_2.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        character_viewer_2.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        character_viewer_1.character_attribute_data,
        name="character_attribute_data",
    ),
    # character finder
    path(
        "character_finder", character_finder.character_finder, name="character_finder"
    ),
    path(
        "character_finder_data",
        character_finder.CharacterFinderListJson.as_view(),
        name="character_finder_data",
    ),
    path(
        "character_finder_list_fdd_data",
        character_finder.character_finder_list_fdd_data,
        name="character_finder_list_fdd_data",
    ),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "user_compliance_report_data",
        reports.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        reports.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        reports.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    # data export
    path("data-export/", data_export.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        data_export.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        data_export.download_export_file,
        name="download_export_file",
    ),
    # admin
    path(
        "admin/create-skillset-from-fitting",
        admin.admin_create_skillset_from_fitting,
        name="admin_create_skillset_from_fitting",
    ),
    path(
        "admin/create-skill-set-from-skill-plan",
        admin.admin_create_skillset_from_skill_plan,
        name="admin_create_skillset_from_skill_plan",
    ),
]

memberaudit/views/character_finder.py
"""Character finder views."""

from dj_datatables_view.base_datatable_view import BaseDatatableView

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Case, F, Q, Value, When
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html, format_html_join
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from allianceauth.eveonline.models import EveCharacter
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag
from app_utils.views import (
    bootstrap_icon_plus_name_html,
    fontawesome_link_button_html,
    yesno_str,
)

from memberaudit import __title__
from memberaudit.models import General

from ._common import add_common_context

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("memberaudit.finder_access")
def character_finder(request) -> HttpResponse:
    """Render view for character finder."""
    context = {"page_title": _("Character Finder")}
    return render(
        request,
        "memberaudit/character_finder.html",
        add_common_context(request, context),
    )


# pylint: disable=too-many-ancestors
class CharacterFinderListJson(
    PermissionRequiredMixin, LoginRequiredMixin, BaseDatatableView
):
    """Server based datatable view for character finder."""

    model = EveCharacter
    permission_required = "memberaudit.finder_access"
    columns = [
        "character",
        "character_organization",
        "main_character",
        "main_organization",
        "state_name",
        "actions",
        "alliance_name",
        "corporation_name",
        "main_alliance_name",
        "main_corporation_name",
        "main_str",
        "unregistered_str",
        "character_id",
    ]

    # define column names that will be used in sorting
    # order is important and should be same as order of columns
    # displayed by datatables. For non sortable columns use empty
    # value like ''
    order_columns = [
        "character_name",
        "corporation_name",
        "character_ownership__user__profile__main_character__character_name",
        "character_ownership__user__profile__main_character__corporation_name",
        "character_ownership__user__profile__state__state_name",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]

    def get_initial_queryset(self):
        """Return initial queryset for this view."""
        return self.initial_queryset(self.request)

    @classmethod
    def initial_queryset(cls, request):
        """Return initial queryset for this view."""
        accessible_users = list(General.accessible_users(user=request.user))
        my_filter = Q(character_ownership__user__in=accessible_users)
        if request.user.has_perm("memberaudit.view_everything"):
            my_filter |= Q(memberaudit_character__isnull=False)
        elif request.user.has_perm("memberaudit.view_shared_characters"):
            my_filter |= Q(memberaudit_character__is_shared=True)
        eve_characters = EveCharacter.objects.select_related(
            "memberaudit_character",
            "character_ownership__user",
            "character_ownership__user__profile__main_character",
            "character_ownership__user__profile__state",
        ).filter(my_filter)
        return (
            eve_characters.annotate(
                unregistered_str=Case(
                    When(memberaudit_character=None, then=Value("yes")),
                    default=Value("no"),
                )
            )
            .annotate(
                is_orphan=Case(
                    When(character_ownership__isnull=True, then=Value(1)),
                    default=Value(0),
                )
            )
            .annotate(state_name=F("character_ownership__user__profile__state__name"))
        )

    def filter_queryset(self, qs):
        """use parameters passed in GET request to filter queryset"""

        qs = self._apply_search_filter(
            qs, 4, "character_ownership__user__profile__state__name"
        )
        qs = self._apply_search_filter(qs, 6, "alliance_name")
        qs = self._apply_search_filter(qs, 7, "corporation_name")
        qs = self._apply_search_filter(
            qs, 8, "character_ownership__user__profile__main_character__alliance_name"
        )
        qs = self._apply_search_filter(
            qs,
            9,
            "character_ownership__user__profile__main_character__corporation_name",
        )
        qs = self._apply_search_filter(
            qs, 10, "character_ownership__user__profile__main_character__character_name"
        )
        qs = self._apply_search_filter(qs, 11, "unregistered_str")

        search = self.request.GET.get("search[value]", None)
        if search:
            qs = qs.filter(
                Q(character_name__icontains=search)
                | Q(
                    character_ownership__user__profile__main_character__character_name__icontains=search
                )
            )
        return qs

    def _apply_search_filter(self, qs, column_num, field):
        my_filter = self.request.GET.get(f"columns[{column_num}][search][value]", None)
        if my_filter:
            if self.request.GET.get(f"columns[{column_num}][search][regex]", False):
                kwargs = {f"{field}__iregex": my_filter}
            else:
                kwargs = {f"{field}__istartswith": my_filter}
            return qs.filter(**kwargs)
        return qs

    def render_column(self, row, column):
        result = self._render_column_auth_character(row, column)
        if result:
            return result
        result = self._render_column_main_character(row, column)
        if result:
            return result
        result = self._render_column_memberaudit_character(row, column)
        if result:
            return result
        return super().render_column(row, column)

    def _render_column_auth_character(self, row, column):
        if column == "character_id":
            return row.character_id
        alliance_name = row.alliance_name if row.alliance_name else ""
        if column == "character_organization":
            return format_html(
                "{}<br><em>{}</em>",
                row.corporation_name,
                alliance_name,
            )
        if column == "alliance_name":
            return alliance_name
        if column == "corporation_name":
            return row.corporation_name
        return None

    def _render_column_main_character(self, row, column):
        try:
            main_character = row.character_ownership.user.profile.main_character
        except ObjectDoesNotExist:
            main_character = None
        is_main = main_character == row
        main_alliance_name = (
            main_character.alliance_name
            if main_character and main_character.alliance_name
            else ""
        )
        if column == "main_character":
            if main_character:
                return bootstrap_icon_plus_name_html(
                    main_character.portrait_url(),
                    main_character.character_name,
                    avatar=True,
                )
            return ""
        if column == "main_organization":
            if main_character:
                return format_html(
                    "{}<br><em>{}</em>",
                    main_character.corporation_name,
                    main_alliance_name,
                )
            return ""
        if column == "main_alliance_name":
            return main_alliance_name if main_character else ""
        if column == "main_corporation_name":
            return main_character.corporation_name if main_character else ""
        if column == "main_str":
            if main_character:
                return yesno_str(is_main)
            return ""
        return None

    def _render_column_memberaudit_character(self, row, column):
        try:
            character = row.memberaudit_character
        except ObjectDoesNotExist:
            character = None
            character_viewer_url = ""
        else:
            character_viewer_url = reverse(
                "memberaudit:character_viewer", args=[character.pk]
            )
        if column == "character":
            try:
                is_main = row.character_ownership.user.profile.main_character == row
            except ObjectDoesNotExist:
                is_main = False
            icons = []
            if is_main:
                icons.append(
                    mark_safe('<i class="fas fa-crown" title="Main character"></i>')
                )
            if character and character.is_shared:
                icons.append(
                    mark_safe('<i class="far fa-eye" title="Shared character"></i>')
                )
            if not character:
                icons.append(
                    mark_safe(
                        '<i class="fas fa-exclamation-triangle" title="Unregistered character"></i>'
                    )
                )
            character_text = format_html_join(
                mark_safe("&nbsp;"), "{}", ([html] for html in icons)
            )
            if row.is_orphan:
                character_text += mark_safe(" [orphan]")
            return bootstrap_icon_plus_name_html(
                row.portrait_url(),
                row.character_name,
                avatar=True,
                url=character_viewer_url,
                text=character_text,
            )
        if column == "actions":
            if character_viewer_url:
                actions_html = fontawesome_link_button_html(

memberaudit/templates/memberaudit/base.html
{% extends 'allianceauth/base.html' %}

{% block page_title %}
    {{ page_title|striptags }} - {{ app_title }}
{% endblock %}

{% block content %}
    <br />
    <div class="aa-memberaudit">
        {% include 'memberaudit/partials/menu.html' %}
        <h2 class="text-left">{{ page_title }}</h2>
        {% block details %}{% endblock %}
    </div>
{% endblock %}

memberaudit/templates/memberaudit/data_export.html
{% extends 'memberaudit/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Topics' %}</h3>
        </div>
        <div class="panel-body">
            <table id="tbl_data_exports" class="table table-striped">
                <thead>
                    <th>{% translate 'Name' %}</th>
                    <th>{% translate 'Description' %}</th>
                    <th>{% translate 'Rows' %}</th>
                    <th>{% translate 'Export file age' %}</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for topic in topics %}
                        <tr>
                            <td>{{ topic.title }}</td>
                            <td>{{ topic.description }}</td>
                            <td>{{ topic.rows|intcomma }}</td>
                            <td>{{ topic.last_updated_at|timesince|default:"no file" }}</td>
                            <td>
                                {% if topic.has_file %}
                                    <a class="btn btn-primary" href="{% url 'memberaudit:download_export_file' topic.value %}">Download</a>
                                {% else %}
                                    <a class="btn btn-primary" href="#" disabled>Download</a>
                                {% endif %}
                                {% if topic.update_allowed %}
                                    <a class="btn btn-default" href="{% url 'memberaudit:data_export_run_update' topic.value %}">Update now</a>
                                {% else %}
                                    <a class="btn btn-default" href="#" disabled>Update now</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class="text-muted">
                {% blocktranslate with amount_of_characters=character_count|intcomma %}Export files contain the complete data of all {{ amount_of_characters }} characters known to Member Audit.{% endblocktranslate %}
                {% blocktranslate %}They are in CSV format and zipped.{% endblocktranslate %}
                {% blocktranslate %}Existing export files are updated after {{ minutes_until_next_update }} minutes.{% endblocktranslate %}
            </p>
        </div>
    </div>
{% endblock details %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/data_export.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

memberaudit/templates/memberaudit/launcher.html
{% extends 'memberaudit/base.html' %}
{% load static %}

{% block details %}

    {% include 'memberaudit/partials/launcher/dashboard.html' %}
    {% include 'memberaudit/partials/launcher/characters.html' %}

{% endblock details %}

{% block extra_javascript %}
    <script type="application/javascript" src="{% static 'memberaudit/js/dashboard.js' %}"></script>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/launcher.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/dashboard.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

memberaudit/templates/memberaudit/reports.html
{% extends 'memberaudit/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div>
        {% include 'memberaudit/partials/reports/tabs_navigation.html' %}

        <div class="panel panel-default panel-tabs">
            <div class="panel-body">
                <!-- Tab panes -->
                <div class="tab-content">
                    {% include 'memberaudit/partials/reports/tabs/user_compliance.html' %}
                    {% include 'memberaudit/partials/reports/tabs/corporation_compliance.html' %}
                    {% include 'memberaudit/partials/reports/tabs/skill_sets.html' %}
                </div>
            </div>

        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/dataTables.rowGroup.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/filterDropDown.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#tab_user_compliance').DataTable({
                ajax: {
                    url: '{% url 'memberaudit:user_compliance_report_data' %}',
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    {
                        data: 'main',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'state' },
                    {
                        data: 'organization',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'registered_str' },
                    { data: 'compliance_str' },
                    { data: 'total_chars' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                ],
                columnDefs: [
                    { "visible": false, "targets": [ 6, 7 ] },
                ],
                order: [ [ 0, "asc" ] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 1,
                            title: "{% translate 'State' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Alliance' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 7,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 3,
                            title: "{% translate 'Registered?' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 4,
                            title: "{% translate 'Compliant?' %}",
                            maxWidth: "12em"
                        }
                    ],
                    bootstrap: true
                },
                createdRow: function( row, data, dataIndex )
                {
                    if (data['is_compliant']){
                        $(row).addClass('success');
                    }
                    else if (data['is_registered']){
                        $(row).addClass('warning');
                    }
                    else {
                        $(row).addClass('danger');
                    }
                }
            });

            $('#tab_corporation_compliance').DataTable({
                ajax: {
                    url: '{% url 'memberaudit:corporation_compliance_report_data' %}',
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    {
                        data: 'organization_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'mains_count' },
                    { data: 'characters_count' },
                    { data: 'compliance_percent' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                    { data: 'is_compliant_str' },
                ],
                columnDefs: [
                    { "visible": false, "targets": [ 4, 5, 6 ] },
                ],
                order: [ [ 0, "asc" ] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 4,
                            title: "{% translate 'Alliance' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 5,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Compliant?' %}",
                            maxWidth: "12em"
                        },
                    ],
                    autoSize: false,
                    bootstrap: true
                },
                createdRow: function( row, data, dataIndex )
                {
                    if (data['is_compliant']){
                        $(row).addClass('success');
                    }
                    else if (data['is_partly_compliant']){
                        $(row).addClass('warning');
                    }
                    else {
                        $(row).addClass('danger');
                    }
                }
            });

            $('#tab_skill_sets').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:skill_sets_report_data' %}",
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    { data: 'group' },
                    { data: 'main_html' },
                    { data: 'state' },
                    { data: 'organization_html' },
                    { data: 'character_html' },
                    { data: 'has_required' },

                    /* hidden columns */
                    { data: 'alliance' },
                    { data: 'corporation' },
                    { data: 'has_required_str' },
                    { data: 'is_doctrine_str' },
                    { data: 'is_main_str' },
                ],
                order: [[0, "asc"], [1, "asc"], [4, "asc"]],
                rowGroup: {
                    dataSrc: 'group',
                    className: 'table-group'
                },
                columnDefs: [
                    { "visible": false, "targets": [0, 6, 7, 8, 9, 10] }
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 0,
                            title: "{% translate 'Groups' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 2,
                            title: "{% translate 'State' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Alliance' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 7,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 8,
                            title: "{% translate 'Required Skills?' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 9,
                            title: "{% translate 'Doctrine?' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 10,
                            title: "{% translate 'Main?' %}",
                            maxWidth: "12em"
                        }
                    ],
                    autoSize: false,
                    bootstrap: true
                }
            });

        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/reports.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}

{% endblock %}